project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Jen (Andy) Chuang"
  navbar:  
#    background: primary
    background: "#eeeeee"#"#0a1952"
    style: "docked"
    left:
      - href: index.qmd
        text: Home
      - research.qmd
#      - teaching.qmd
      - cv.qmd
  cookie-consent: true
  google-analytics: "G-P59RQK1WTV"
  site-url: 'https://yujen-chuang.github.io'
  site-path: '/'
  
format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    page-layout: full
    fontcolor: black
#    mainfont: "Gill Sans"
    fontsize: 1.15rem
    line-height: 160%;


    
editor: visual

