project:
  type: website
  output-dir: docs
  
website:
  title: "Yu-Jen (Andy) Chuang"
  favicon: images/favicon1.png
  cookie-consent: true
  google-analytics: "G-P59RQK1WTV"
  site-url: 'https://yujen-chuang.com'
  repo-url: 'https://github.com/yujen-chuang/website'

  open-graph:
    title: "Yu-Jen (Andy) Chuang"
    site-name: "Yu-Jen (Andy) Chuang"
  
  navbar:  
#    background: primary
    background: "#eeeeee"#"#0a1952"
    style: "docked"
    right:
      - href: index.qmd
        text: About
      - research.qmd
      - cv.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    page-layout: full
    fontcolor: black
#    mainfont: "Gill Sans"
    fontsize: 1.15rem
    line-height: 160%;

resources:
  - CNAME
    
editor: visual

