---
title: "CV"
format:
  html:
    toc: false
    css: styles.css
---

## Education

**Ph.D. in Economics**, Goethe University Frankfurt (GSEFM), 2022-Present

**M.Sc. in Quantitative Economics**, Goethe University Frankfurt (GSEFM), 2022-Present

**M.Sc. in Economics**, University of Mannheim, 2022

**B.B.A. in Business Economics**, City University of Hong Kong, 2020

**B.A. in Economics**, National Taiwan University, 2020

## Conference Presentations

::: {.callout-important appearance="simple" icon="false"}
**2025**

------------------------------------------------------------------------

-   **CMIC (China Marketing International Conference)**, *Xuzhou, China* (scheduled)

-   **SCECR (Symposium on Statistical Challenges in E-Commerce Research)**, *Paphos, Cyprus* (scheduled)

-   **ISMS Marketing Science Conference**, *Washington D.C.* (scheduled)

-   **EMAC (European Marketing Academy Annual Conference)**, *Madrid, Spain* (scheduled)
:::

::: {.callout-important appearance="simple" icon="false"}
**2024**

------------------------------------------------------------------------

-   **WISE (Workshop on Information Systems and Economics)**, *Bangkok, Thailand*

-   **SCECR (Symposium on Statistical Challenges in E-Commerce Research)**, *Lisbon, Portugal*

-   **DPE (Digital Platform Ecosystems) Forum**, *Passau, Germany*

-   **EMAC (European Marketing Academy Annual Conference)**, *Bucharest, Romania*
:::

## Teaching

**Goethe University Frankfurt**

::: {.callout-note collapse="true" style="gray" appearance="minimal" icon="false"}
## Applications of Generative AI in Marketing

------------------------------------------------------------------------

-   **Type:** Bachelor's Level, Seminar, Co-teach with Prof. Bernd Skiera

-   **Period:** Summer 2025

-   This seminar equips students with a comprehensive understanding of generative AI and its applications in marketing. Students will engage in reading academic papers, discussing AI models, and applying generative AI in practical business scenarios.
:::

::: {.callout-warning collapse="true" style="gray" appearance="minimal" icon="false"}
# Econometrics in Management / Marketing

------------------------------------------------------------------------

-   **Type:** Bachelor's Level, Course, Co-teach with Prof. Bernd Skiera

-   **Period:** Summer 2025

-   This course is designed to deepen students' understanding of marketing analytics—specifically, the use of econometric methods and concepts to improve marketing decision-making. We aim to enable students to apply econometric methods to solve economic and marketing-related problems.
:::

::: {.callout-note collapse="true" style="gray" appearance="minimal" icon="false"}
## Data Mining in Marketing: Data-Driven Customer Analytics with Machine Learning

------------------------------------------------------------------------

-   **Type:** Master's Level, Seminar, Co-teach with Hon. Prof. Martin Schmidberger (Head of Customer Analytics at ING Germany)

-   **Period:** Summer 2025

-   This seminar focuses on "predictive modeling" as a challenge in marketing. Using a real-life dataset, we will forecast and predict customers' purchase behavior and derive models that help optimize the efficiency of marketing campaigns. We will present both the process of data mining and the most relevant machine learning algorithms to predict customer (buying) behavior.
:::

::: {.callout-note collapse="true" style="gray" appearance="minimal" icon="false"}
## Generative AI in Marketing

------------------------------------------------------------------------

-   **Type:** Master's Level, Seminar, Co-teach with Prof. Bernd Skiera

-   **Period:** Winter 2024/25

-   This seminar explores the transformative impact of generative AI technologies on marketing. Students will gain an understanding of the underlying AI models and their applications in marketing. We tailor the seminar for students eager to harness the power of AI to drive innovation in marketing, with insights and strategies that can be applied to other business fields as well.
:::

::: {.callout-tip collapse="true" appearance="simple" icon="false"}
## Bachelor and Master Theses Supervision

------------------------------------------------------------------------

-   **Type:** Bachelor's Level (x7) & Master's Level (x3), Co-supervise with Prof. Bernd Skiera

-   **Period:** Summer 2025, Winter 2024/25, Summer 2024
:::
